spring.application.name=Capstone System

# default active profile
spring.profiles.active=local

app.name=Capstone System
app.formatting.date-pattern=yyyy-MM-dd
app.formatting.time-pattern=HH:mm:ss
app.supported-formats[0]=yyyy-MM-dd
app.supported-formats[1]=dd-MM-yyyy
app.supported-formats[2]=MM/dd/yyyy

my.values=one-two-three
